(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const names = { a: '차분한 블루', b: '친근한 세이지', c: '선명한 라벤더' };
  const notes = { a: 'A · 한눈에 읽히는 정보, 여백이 있는 차분한 시작', b: 'B · 연결부터 첫 게임까지, 한 단계씩 따라가는 시작', c: 'C · 게임을 중심에 두고, 선명한 구역으로 나눈 시작' };
  const params = new URLSearchParams(location.search);
  let theme = ['a','b','c'].includes(params.get('theme')) ? params.get('theme') : 'a';
  let screen = ['home','training','records'].includes(params.get('screen')) ? params.get('screen') : 'home';
  let device = params.get('device') === 'mobile' ? 'mobile' : 'desktop';
  let connected = false, calibrated = false, playing = false, force = 56, hold = 0, seconds = 20, score = 0, interval = null, toastTimer;
  const paths = {
    home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',
    game:'M6 8h12c3 0 5 11 2 12-2 1-4-3-5-3H9c-1 0-3 4-5 3-3-1 0-12 2-12ZM8 10v5m-2.5-2.5h5M16 11h.01M18 14h.01',
    chart:'M4 4v16h17M8 15v-4m5 4V7m5 8v-6',
    arrow:'M5 12h14m-6-6 6 6-6 6',
    back:'M19 12H5m6-6-6 6 6 6',
    check:'m5 12 4 4L19 6',
    time:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',
    bluetooth:'m6 7 12 10-6 5V2l6 5L6 17',
    grip:'M7 12V5a2 2 0 0 1 4 0v6-8a2 2 0 0 1 4 0v8-6a2 2 0 0 1 4 0v10c0 5-2 7-6 7h-1c-3 0-4-1-6-4l-3-5a2 2 0 0 1 3-2l3 3',
    balloon:'M19 9c0 5-4 8-7 8S5 14 5 9a7 7 0 0 1 14 0ZM12 17l-2 3h4l-2-3m0 3c4 1-3 2 1 3',
    crane:'M4 3h16M12 3v9m-5-3h10v4l-5 5-5-5ZM7 21h10',
    music:'M9 18V5l11-2v13M9 18c0 3-6 4-6 1s6-4 6-1ZM20 16c0 3-6 4-6 1s6-4 6-1Z',
    boat:'M4 13h13a4 4 0 0 1 0 8H7a5 5 0 0 1-3-8Zm7 0V7h4v6M7 16h.01M11 16h.01M15 16h.01M3 9h3M2 5h2',
    info:'M12 11v6m0-10h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',
    pause:'M8 5v14M16 5v14',
    play:'m8 4 12 8-12 8Z'
  };
  function icon(name,cls='icon') { return `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name] || paths.game}"/></svg>`; }
  function brand(){ return `<a href="#" class="brand" data-screen="home"><svg class="brand-mark" viewBox="0 0 36 36" fill="none" aria-hidden="true"><path class="mark-stroke" d="M9 25V13a8 8 0 0 1 16 0v3M15 26V15a2 2 0 0 1 4 0v12M25 21v5a7 7 0 0 1-7 7" stroke-width="3.5" stroke-linecap="round"/></svg>ReGrip</a>`; }
  function scene(interactive=false){ return `<div class="scene-wrap${interactive?' interactive-scene':''}"><svg class="scene-svg" viewBox="0 0 500 350" preserveAspectRatio="xMidYMid slice" role="img" aria-label="풍선을 목표 구간에 유지하는 게임 미리보기"><path class="sky-cloud" d="M-40 108h182c0-15-18-20-31-17 0-21-17-35-36-31-18-20-43-9-47 9-28-4-39 15-36 27Z"/><path class="sky-cloud" d="M337 262h196c-2-19-21-24-37-20-6-24-30-31-48-16-25-17-50 0-52 17-29-3-40 7-40 19Z"/><rect class="target-fill" x="0" y="88" width="500" height="100"/><path class="target-line" d="M0 89h500M0 187h500" stroke-width="1" stroke-dasharray="5 6"/><text x="24" y="111">여기서 3초 유지</text><g class="floating-balloon" id="${interactive?'live-balloon':'preview-balloon'}" transform="translate(280,140)"><path d="M-3 66c-16 17 14 25 0 45" fill="none" stroke="#72868a" stroke-width="1.5"/><path class="scene-balloon" d="M0 58C-10 56-42 30-42-4a42 45 0 1 1 84 0C42 30 10 56 0 58Z"/><path class="balloon-rib" d="M0-49C-27-29-29 20 0 58M0-49C27-29 29 20 0 58" fill="none" stroke-width="1.5" opacity=".55"/><path d="m0 57-6 9H6Z" class="scene-balloon"/><ellipse cx="-18" cy="-21" rx="7" ry="13" fill="#fff" opacity=".32" transform="rotate(24 -18 -21)"/></g><path d="M0 335c80-25 141-16 208 0 74-29 150-31 292-3v18H0Z" fill="currentColor" opacity=".035"/></svg>${!interactive?'<div class="scene-caption"><span>PRESS · HOLD · RELEASE</span><span>풍선 게임</span></div>':''}</div>`; }
  function nav(){return `<header class="product-header">${brand()}<nav class="product-nav" aria-label="앱 메뉴">${[['home','home','오늘'],['training','game','훈련'],['records','chart','기록']].map(([id,ic,label])=>`<button class="nav-btn ${screen===id?'active':''}" data-screen="${id}" ${screen===id?'aria-current="page"':''}>${icon(ic)}${label}</button>`).join('')}</nav><div class="header-right"><button class="sensor-status" data-action="connect"><span class="status-dot ${connected?'on':''}"></span>${connected?'센서 연결 · 예시':'센서 연결하기'}${icon('bluetooth')}</button><span class="avatar">지</span></div></header>`;}
  function week(){return `<div class="week-days">${['월','화','수','목','금','토','일'].map((d,i)=>`<div class="day"><span class="day-mark ${[0,2,3].includes(i)?'done':i===5?'today':''}">${[0,2,3].includes(i)?icon('check'):i===5?'5':'·'}</span>${d}</div>`).join('')}</div>`;}
  function meta(){return `<div class="meta-row"><span class="tag success">쉬움</span>${icon('time')}<span>2분</span><i class="dot"></i><span>힘 유지하기</span></div>`;}
  function gameCards(){return [['crane','크레인','쥐고, 천천히 놓기'],['music','리듬 펌프','박자에 맞춰 쥐기'],['boat','잠수함','힘의 크기 조절하기']].map(([i,t,d])=>`<button class="mini-game" data-action="other-game" data-game="${t}"><span class="game-icon">${icon(i)}</span><span><h3>${t}</h3><p>${d}</p></span>${icon('arrow','arrow')}</button>`).join('');}
  function sensorStrip(){return `<section class="sensor-strip"><div class="sensor-strip-title"><div class="device-icon">${icon(connected?'bluetooth':'grip')}</div><div><h3>${calibrated?'내 손에 맞게 준비됐어요':connected?'내 손에 맞는 기준을 설정해요':'센서와 함께 시작해 볼까요?'}</h3><p>${calibrated?'보정 완료 · 오른손 · 예시 센서':connected?'손을 편하게 놓고, 쥐는 힘의 범위를 맞춰 주세요.':'연결 후 나에게 맞게 보정하면 준비가 끝나요.'}</p></div></div><button class="secondary" data-action="${connected?'calibrate':'connect'}">${calibrated?'다시 보정하기':connected?'보정 시작':'센서 연결'}${icon('arrow')}</button></section>`;}
  function footer(){return `<footer class="product-footer"><span>조금씩, 내 손의 속도로.</span><span>예시 화면 · 오른손 기준</span></footer>`;}
  function homeA(){return `<div class="intro a-intro"><p class="eyebrow">오늘의 리그립</p><h1>손의 감각을 깨우는,<br>가벼운 2분.</h1><p>처음이라면 짧은 연습부터 시작해 보세요.</p></div><section class="a-hero"><div class="a-hero-copy"><span class="eyebrow">오늘의 추천 훈련</span><h2>풍선을 천천히,<br>초록 구간까지.</h2><p>힘을 주어 풍선을 올리고,<br>알맞은 힘으로 3초간 유지해요.</p>${meta()}<div class="action-row"><button class="primary" data-screen="training">20초 연습${icon('arrow')}</button><button class="secondary" data-screen="training">훈련 살펴보기</button></div></div>${scene()}</section><div class="flat-stats"><div class="flat-stat"><span>이번 주 훈련</span><strong>3<small>일</small></strong></div><div class="flat-stat"><span>완료한 게임</span><strong>8<small>회</small></strong></div><div class="flat-stat"><span>총 훈련 시간</span><strong>14<small>분</small></strong></div></div><div class="section-title"><h2>다른 움직임도 연습해요</h2><button class="text-btn" data-screen="training">훈련 보기${icon('arrow')}</button></div><div class="games-grid">${gameCards()}</div>${sensorStrip()}`;}
  function homeB(){return `<div class="intro"><p class="eyebrow">나의 첫 리그립</p><h1>오늘도 한 걸음,<br>내 손의 속도로.</h1><p>서두르지 않아도 괜찮아요. 하나씩 시작해 볼까요?</p></div><div class="b-layout"><section class="b-path" aria-label="오늘의 시작 단계"><div class="b-step"><div class="step-number">1</div><div class="step-content"><div class="step-title"><h3>센서 준비하기</h3><span class="tag ${calibrated?'success':''}">${calibrated?'완료':'먼저 확인'}</span></div><p>연결하고, 내 손에 맞게 보정해요.</p><button class="text-btn" data-action="${connected?'calibrate':'connect'}">${connected?'보정하기':'센서 연결'}${icon('arrow')}</button></div></div><div class="b-step current"><div class="step-number">2</div><div class="step-content"><div class="b-training-copy"><span class="tag success">오늘의 작은 시작</span><h2 style="margin-top:13px">풍선 하나 띄워 볼까요?</h2><p>초록 구간에서 3초만 편하게 유지해요.</p>${meta()}<div class="action-row"><button class="primary" data-screen="training">20초만 연습해 보기${icon('arrow')}</button><button class="secondary" data-action="howto">방법 보기</button></div></div><div class="b-scene">${scene()}</div></div></div><div class="b-step future"><div class="step-number">3</div><div class="step-content"><h3>오늘의 움직임 돌아보기</h3><p>작은 시도도 차곡차곡 쌓여요.</p><button class="text-btn" data-screen="records">기록 둘러보기${icon('arrow')}</button></div></div></section><aside class="b-aside"><section class="b-note"><p class="eyebrow">이번 주의 발자국</p><h2>벌써 3일 함께했어요</h2><p>짧게라도 꾸준히,<br>나만의 리듬을 만들어 가요.</p>${week()}<div class="progress-line"><span></span></div><div class="progress-legend"><span>이번 주 목표</span><span>3 / 5일</span></div></section><div class="b-side-game"><span class="game-icon">${icon('music')}</span><h3 style="margin-top:13px">다음엔 리듬 펌프</h3><p>박자에 맞춰 쥐고 놓는<br>색다른 움직임을 만나 보세요.</p><button class="text-btn" data-action="other-game" data-game="리듬 펌프">어떤 게임인가요?${icon('arrow')}</button></div></aside></div>${sensorStrip()}`;}
  function homeC(){return `<div class="intro intro-line"><div><p class="eyebrow">PLAY AT YOUR PACE</p><h1>오늘의 플레이,<br>가볍게 시작해요.</h1><p>내 손의 움직임이 게임이 되는 시간.</p></div><span class="small-label">9월 5일 토요일</span></div><section class="c-hero"><div class="c-hero-copy"><span class="tag">첫 게임으로 추천</span><h2>조금 더 높이.<br>조금 더 천천히.</h2><p>풍선을 띄우며 힘을 조절해 보세요.</p>${meta()}<div class="action-row"><button class="primary" data-screen="training">풍선 플레이${icon('arrow')}</button><button class="text-btn" data-action="howto">방법 보기</button></div></div>${scene()}</section><div class="c-bottom"><section class="c-habit"><p class="eyebrow">MY WEEK</p><h2>세 번의 좋은 시작.</h2><p>이번 주 3일, 14분 동안 함께했어요.</p>${week()}</section><section class="c-library" aria-label="다른 게임">${gameCards()}</section></div>${sensorStrip()}`;}
  function game(){return `<div class="back-row"><button class="text-btn" data-screen="home">${icon('back')}오늘의 훈련</button><span class="tag practice">시뮬레이션 미리보기</span></div><div class="game-page-title"><h1>풍선 띄우기</h1><p>초록 구간에서 알맞은 힘으로 3초간 유지해요.</p></div><div class="game-layout"><div class="game-stage">${scene(true)}<div class="game-hud"><div class="hud-unit">남은 연습<strong id="game-time">0:20</strong></div><div class="hud-unit">띄운 풍선<strong id="game-score">0</strong></div></div><div class="game-feedback" id="game-feedback">준비되면 연습을 시작해 주세요.</div><div class="game-play-overlay" id="game-overlay"><div class="game-ready-box"><span class="tag success">쉬움 · 최대 20초</span><h2 style="margin-top:17px">내 손의 힘을 만나볼까요?</h2><p>옆의 슬라이더로 힘의 크기를 바꿔 보세요. 연습 결과는 기록되지 않아요.</p><div class="action-row"><button class="primary" data-action="start-play">연습 시작${icon('play')}</button></div></div></div></div><aside class="game-controls"><div class="control-block"><h3>힘 조절 미리보기</h3><div class="force-value"><span id="force-value">56</span><small>%</small></div><label for="force-slider" class="small-label">슬라이더로 힘의 크기를 바꿔 보세요</label><input class="force-range" id="force-slider" type="range" min="0" max="100" value="56" aria-label="게임에 적용할 힘"><div class="range-labels"><span>힘 풀기</span><span>세게 쥐기</span></div><div class="hold-track"><span id="hold-fill"></span></div><p id="hold-value">목표 범위 46–74% · 3초 유지</p></div><div class="control-block"><h3>이렇게 움직여요</h3><ol class="instruction-list"><li><b>1</b>힘을 주어 풍선을 올려요.</li><li><b>2</b>초록 범위의 힘으로 유지해요.</li><li><b>3</b>천천히 힘을 풀고 쉬어요.</li></ol></div><button class="secondary" data-action="pause-play" id="pause-play" disabled>${icon('pause')}일시정지</button></aside></div>`;}
  function records(){return `<div class="intro"><p class="eyebrow">나의 훈련 기록</p><h1>작은 움직임이<br>차곡차곡 쌓이고 있어요.</h1><p>최근 일주일의 예시 기록을 확인해 보세요.</p></div><div class="records-overview"><div class="record-stat"><span>훈련한 날</span><strong>3<small>일</small></strong></div><div class="record-stat"><span>총 훈련 시간</span><strong>14<small>분</small></strong></div><div class="record-stat"><span>완료한 게임</span><strong>8<small>회</small></strong></div></div><section class="record-chart"><div class="chart-top"><h3>이번 주 움직인 시간</h3><span class="tag">8.31 – 9.6 · 예시</span></div><div class="bars" aria-label="월요일 4분, 수요일 6분, 목요일 4분, 나머지 0분">${[62,2,94,62,2,2,2].map((v,i)=>`<div class="bar ${i===2?'current':''}" style="--bar-h:${v}%"></div>`).join('')}</div><div class="bar-labels">${['월','화','수','목','금','토','일'].map(t=>`<span>${t}</span>`).join('')}</div></section><div class="section-title"><h2>최근 훈련</h2><span class="small-label">입력 출처를 함께 표시해요</span></div><table class="records-table"><thead><tr><th>게임</th><th>날짜</th><th>입력</th><th class="record-duration">시간</th><th>결과</th></tr></thead><tbody><tr><td>풍선 띄우기</td><td>9월 3일</td><td><span class="tag success">센서</span></td><td class="record-duration">2분</td><td>6개</td></tr><tr><td>리듬 펌프</td><td>9월 2일</td><td><span class="tag practice">시뮬레이션</span></td><td class="record-duration">2분</td><td>18회</td></tr><tr><td>잠수함</td><td>8월 31일</td><td><span class="tag">출처 미확인</span></td><td class="record-duration">1분 30초</td><td>19개</td></tr></tbody></table><p class="record-source-note">센서·시뮬레이션 기록은 구분해 볼 수 있어요. 예전 기록에 입력 정보가 없으면 ‘출처 미확인’으로 표시해요.</p><div class="empty-help">${icon('info')}<p>20초 연습은 기록과 보상에 포함되지 않아요.<br>본게임을 마치면 훈련 기록이 남아요.</p></div>`;}
  function updateUrl(){const p=new URLSearchParams(location.search);p.set('theme',theme);p.set('screen',screen);if(device==='mobile')p.set('device','mobile');else p.delete('device');history.replaceState(null,'',`${location.pathname}?${p}`);}
  function render(){clearInterval(interval);playing=false;force=56;hold=score=0;seconds=20;$('app').innerHTML=`<div class="product theme-${theme}">${nav()}<main class="product-main" id="product-main" tabindex="-1">${screen==='home'?({a:homeA,b:homeB,c:homeC}[theme])():screen==='training'?game():records()}${footer()}</main></div>`;document.querySelectorAll('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===theme)));document.querySelectorAll('[data-device]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.device===device)));$('device-frame').classList.toggle('mobile',device==='mobile');$('direction-note').textContent=notes[theme];let saved;try{saved=localStorage.getItem('regrip_design_choice');}catch{}$('choose-design').textContent=saved===theme?`${theme.toUpperCase()} 선택됨`:'이 디자인 선택';document.title=`ReGrip — ${theme.toUpperCase()}. ${names[theme]}`;updateUrl();}
  function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3600);}
  function dialog(title,body,button,action,ic='grip'){const d=$('preview-dialog');d.innerHTML=`<button class="dialog-close" data-action="close-dialog" aria-label="닫기">×</button><div class="dialog-icon">${icon(ic)}</div><h2 id="dialog-title">${title}</h2>${body}<button class="dialog-action" data-action="${action}">${button}</button><p style="font-size:11px;margin-bottom:0;text-align:center">디자인 미리보기 · 실제 기기와 연결하지 않습니다.</p>`;if(!d.open)d.showModal();}
  function calibration(step=0){if(step===0){dialog('먼저, 손을 편하게 놓아 주세요.','<div class="cal-progress"><span class="active"></span><span></span></div><p>손에 힘을 뺀 상태를 기준으로 삼아요.<br>편안해졌다면 아래 버튼을 눌러 주세요.</p><div class="dialog-reading">0%<small>편하게 놓은 상태 · 예시</small></div>','편한 상태 기록','cal-next');}else{dialog('이번엔 편안한 만큼 쥐어 주세요.','<div class="cal-progress"><span class="active"></span><span class="active"></span></div><p>무리하지 않고 쥘 수 있는 힘을 맞춰요.<br>이 범위를 게임의 기준으로 사용할게요.</p><div class="dialog-reading">100%<small>나에게 맞는 쥐는 힘 · 예시</small></div>','보정 완료','cal-done');}}
  function updateGame(){if(!$('force-value'))return;$('force-value').textContent=force;$('live-balloon').setAttribute('transform',`translate(280,${255-force*2})`);$('hold-fill').style.width=`${Math.min(100,hold/3*100)}%`;$('game-time').textContent=`0:${String(Math.ceil(seconds)).padStart(2,'0')}`;$('game-score').textContent=score;$('hold-value').textContent=hold>0?`${hold.toFixed(1)} / 3초 유지 중`:'목표 범위 46–74% · 3초 유지';if(playing)$('game-feedback').textContent=force>=46&&force<=74?'좋아요. 지금의 힘을 유지해 주세요.':force<46?'조금 더 힘을 주어 보세요.':'천천히 힘을 풀어 보세요.';}
  function play(){playing=true;$('game-overlay').hidden=true;$('pause-play').disabled=false;$('pause-play').innerHTML=`${icon('pause')}일시정지`;clearInterval(interval);interval=setInterval(()=>{if(!playing)return;seconds=Math.max(0,seconds-.1);hold=force>=46&&force<=74?Math.min(3,hold+.1):Math.max(0,hold-.05);if(hold>=3)score=1;updateGame();if(score||seconds<=0){clearInterval(interval);playing=false;$('pause-play').disabled=true;$('game-overlay').hidden=false;$('game-overlay').innerHTML=`<div class="game-ready-box"><span class="tag success">연습 완료</span><h2 style="margin-top:17px">${score?'풍선 하나, 가볍게 성공!':'오늘의 첫 시도를 마쳤어요.'}</h2><p>이 화면은 디자인 미리보기예요.<br>실제 기록과 보상은 저장되지 않았어요.</p><div class="action-row"><button class="primary" data-action="replay">다시 연습</button><button class="secondary" data-screen="home">오늘로 돌아가기</button></div></div>`;}},100);updateGame();}
  document.addEventListener('input',e=>{if(e.target.id==='force-slider'){force=Number(e.target.value);updateGame();}});
  document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.theme){theme=b.dataset.theme;render();return;}if(b.dataset.device){device=b.dataset.device;render();return;}if(b.dataset.screen){e.preventDefault();screen=b.dataset.screen;render();return;}switch(b.dataset.action){case'connect':dialog(connected?'예시 센서가 연결되어 있어요.':'센서를 연결해 볼까요?','<p>실제 화면에서는 주변의 ReGrip 센서를 선택해요. 이 미리보기에서는 연결된 상태를 먼저 확인할 수 있어요.</p>',connected?'보정 화면 보기':'연결된 상태 보기',connected?'calibrate':'connect-done','bluetooth');break;case'connect-done':connected=true;$('preview-dialog').close();render();toast('예시 센서가 연결됐어요. 이제 보정 화면을 확인해 보세요.');break;case'calibrate':connected=true;calibration();break;case'cal-next':calibration(1);break;case'cal-done':calibrated=true;$('preview-dialog').close();render();toast('보정 완료 상태로 바뀌었어요.');break;case'close-dialog':$('preview-dialog').close();break;case'howto':dialog('힘을 주고, 유지하고, 풀어요.','<p>풍선을 초록 구간까지 올린 뒤 알맞은 힘으로 3초간 유지해요. 처음엔 20초 연습으로 천천히 익혀 보세요.</p>','게임 미리보기','show-game','balloon');break;case'show-game':$('preview-dialog').close();screen='training';render();break;case'other-game':dialog(b.dataset.game+' 미리보기','<p>이 목업에서는 대표 게임인 풍선의 준비·플레이 화면을 조작할 수 있어요. 나머지 게임은 같은 디자인으로 이어질 예정이에요.</p>','풍선 화면 체험하기','show-game','game');break;case'start-play':play();break;case'pause-play':playing=!playing;b.innerHTML=playing?`${icon('pause')}일시정지`:`${icon('play')}계속하기`;$('game-feedback').textContent=playing?'준비되면 힘을 조절해 주세요.':'쉬는 중이에요. 준비되면 계속해 주세요.';break;case'replay':screen='training';render();play();break;}});
  $('choose-design').addEventListener('click',()=>{try{localStorage.setItem('regrip_design_choice',theme);}catch{}$('choose-design').textContent=`${theme.toUpperCase()} 선택됨`;toast(`${theme.toUpperCase()}. ${names[theme]}를 선택했어요. 선택은 이 미리보기에만 저장됩니다.`);});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){playing=false;if($('pause-play'))$('pause-play').innerHTML=`${icon('play')}계속하기`;}});
  $('preview-dialog').addEventListener('click',e=>{if(e.target===$('preview-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
  render();
})();
